/**
 * Dumps the content tables from the linked Supabase project into
 * supabase/seed.sql. Every content table is world-readable under RLS, so the
 * publishable key in .env is enough — no service-role key needed.
 *
 *   node scripts/dump-seed.mjs
 *
 * Run this against the OLD project, then `supabase db push` followed by the
 * generated seed.sql against the new one.
 */
import { createClient } from '@supabase/supabase-js'
import { readFileSync, writeFileSync } from 'node:fs'

const env = Object.fromEntries(
  readFileSync('.env', 'utf8')
    .split('\n')
    .filter((l) => l.trim() && !l.startsWith('#'))
    .map((l) => {
      const i = l.indexOf('=')
      return [l.slice(0, i).trim(), l.slice(i + 1).trim()]
    }),
)

const supabase = createClient(env.VITE_SUPABASE_URL, env.VITE_SUPABASE_ANON_KEY)

// Ordered so foreign keys resolve: services.category -> service_categories.name
const TABLES = [
  'service_categories',
  'services',
  'creators',
  'stats',
  'niches',
  'videos',
  'packaging_flips',
  'contact_channels',
  'site_copy',
]

const lit = (v) => {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  if (typeof v === 'number') return String(v)
  return "'" + String(v).replace(/'/g, "''") + "'"
}

const out = [
  '-- Generated by scripts/dump-seed.mjs. Content rows for a fresh project.',
  '-- Safe to re-run: every insert is on-conflict-do-nothing.',
  '',
]

for (const table of TABLES) {
  const { data, error } = await supabase.from(table).select('*')
  if (error) throw new Error(table + ': ' + error.message)
  out.push('-- ' + table + ' (' + data.length + ' rows)')
  if (!data.length) {
    out.push('')
    continue
  }
  const cols = Object.keys(data[0]).filter((c) => c !== 'created_at' && c !== 'updated_at')
  out.push('insert into public.' + table + ' (' + cols.map((c) => '"' + c + '"').join(', ') + ') values')
  out.push(
    data.map((row) => '  (' + cols.map((c) => lit(row[c])).join(', ')  + ')').join(',\n') +
      '\non conflict do nothing;',
  )
  out.push('')
}

writeFileSync('supabase/seed.sql', out.join('\n'))
console.log('wrote supabase/seed.sql (' + out.join('\n').length + ' bytes)')
